version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: project
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: willian.reinaldo@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    restart: always
  postgis:
    image: mdillon/postgis:latest
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "25432:5432"
    restart: always